### ISSUE TITLE
Has Neurio API changed?

### ISSUE THREAD

**Issue by springshim** [jordanh/neurio-python#11]
Hello

I am trying to get API data by using this code.
And I need to get energy history based on each appliance.

However, it seems like there has been some changes in Neurio API.
I used 'get_appliance_stats_by_appliance' function, but the result said I need a location id.
If I put the location id (and slightly changed the __init__.py file), the result is the same with the data from 'get_appliance_event_after_time' function.

<code>
test = nc.get_appliance_stats_by_appliance(appliance_id="JfU94U8uShCHsqwIrIleKw", start="2017-10-21T19:42:54.009Z", end=current_time, per_page=None, page=None, min_power=None)

print(test)

<result>
{'code': 'missing_parameter', 'message': 'This parameter is required: locationId'}

Did I something wrong? Or has Neurio API changed?

**Comment by jordanh** [comment]
It's been a _long_ while since I've looked at the API. I've moved houses and left the old device in place, so it'd be difficult for me to develop a fix for this. Let me write some folks at Neurio, and see if they might be able to whip up a PR...

**Comment by cameo99** [comment]
Hi springshim, 
I tested this locally and it seems to work for me.
However I get the same missing parameter error if I don't supply the end time.
Make sure your end=current_time is not None and is formatted the same as the start time. It should work then

**Comment by springshim** [comment]
Hi Jordanh

I solved this problem. And I checked from Neurio that API hasn't changed.
Thanks for helping me out,

2017-10-31 16:04 GMT-04:00 Cameron Johnson <notifications@github.com>:
