### ISSUE TITLE
error importing neurio module

### ISSUE THREAD

**Issue by larsks** [jordanh/neurio-python#3]
Trying to import the `neurio` module yields the following traceback:

``` python
>>> import neurio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "neurio/__init__.py", line 446
SyntaxError: Non-ASCII character '\xe2' in file neurio/__init__.py on line 447, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
>>> 
```

This is due to the word `location’s` in the doc text for `get_appliance_stats_by_location`.  You can either replace this with an ascii single quote (`'`) or declare the source file to be UTF-8 encoded by adding the following at top:

```
# -*- coding: utf-8 -*-
```

**Comment by jordanh** [comment]
Hey! Thanks a ton! I hadn't run into this one due to my terminal's localization settings. More than happy to fix this fast by replacing the stupid unicode character with a standard ASCII '. However, would you like to submit a pull request? I'd love to count you among the contributors to the module.

**Comment by larsks** [comment]
Sure, happy to. I should be back in front of a computer tomorrow sometime.

**Comment by jordanh** [comment]
@larsks thank's a ton! Much appreciated.
